feat: implements basic features
AG-Develop/rabbitmq-producer-consumer pull request #1
Opened 2022-07-15 11:08 UTC by coff

2022-07-16 07:00 UTC, krzycho1997 requested changes
Również przyczekpa do sensowności trzymania wielu commitów. Warto według mnie rozważyć squash

2022-07-16 07:00 UTC, krzycho1997 commented on .php-cs-fixer.dist.php
> +    'array_syntax' => ['syntax' => 'short'],
Jak w pozostałych, pytanie o default z uwagi na to co jest tutaj:  https://cs.symfony.com/doc/rules/array_notation/array_syntax.html

2022-07-16 07:00 UTC, krzycho1997 commented on src/RabbitMqProducer.php
> +class RabbitMqProducer implements ProducerInterface
Według mnie testy powinny być dla nas must-have. Moim zdaniem nic nie stoi na przeszkodzie, żeby tutaj dać dosłownie jeden unit.

2022-07-16 07:00 UTC, krzycho1997 commented on src/RabbitMqProducer.php
> +        $this->channel->basic_publish(
Widziałbym test, który badał by czy `basic_publish` otrzymuje oczekiwane parametry. Osobiście bez testów bałbym się ruszać nieznany dla siebie kod

2022-07-16 07:00 UTC, krzycho1997 commented on src/RabbitMqConsumer.php
> +class RabbitMqConsumer implements ConsumerInterface
Przetestowałbym również instancję `ConsumerInterface`

2022-07-26 20:45 UTC, ImJustToNy approved these changes
Generalnie podoba mi się ten kod, aczkolwiek położyłbym większą uwagę na jakiejś bardziej ekstensywnej dokumentacji.

2022-07-29 13:51 UTC, coff commented on src/RabbitMqProducer.php
> +class RabbitMqProducer implements ProducerInterface
Zgadzam się... problem w tym, że akurat tutaj nie za bardzo jest co testować... w pozostałych komponentach dodalem testy.

2022-07-29 13:53 UTC, coff commented on src/RabbitMqProducer.php
> +        $this->channel->basic_publish(
No właśnie ja osobiście nie podchodziłbym do tego aż tak kategorycznie. Raczej kładłbym nacisk na testy tam gdzie jest jakaś logika, która w jakichś okolicznościach może zawieść. Tutaj mamy sytuację gdzie metoda przekazuje swoje parametry dalej po prostu do infrastruktury

2022-08-22 11:18 UTC, coff commented
> Również przyczekpa do sensowności trzymania wielu commitów. Warto według mnie rozważyć squash

taki plan aby squash'ować

2022-08-28 20:26 UTC, krzycho1997 commented
@coff co myślisz o squash?

2022-08-29 20:35 UTC, krzycho1997 approved these changes

2022-08-31 18:58 UTC, merged